# -*- coding: utf-8 -*-
"""GRUPO_13_Tarea1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mEeMQtjTUA6xj9IzJ73QQZGG1TKOl9zp

Ejercicio I:
"""

x = 6
if x%2 == 0 and x%3 == 0:
  print("múltiplo de 2 y 3")
elif x % 3 == 0:
  print("múltiplo de 3")
elif x % 2 == 0:
  print("múltiplo de 2")
else:
  print("otro caso")

"""Ejercicio 2"""

for x in range(1,101):
  if x%3 == 0 and x%5 == 0:
    print("fizzbuzz")
  elif x%5 == 0:
    print("Buzz")
  elif x%3 == 0:
    print("fizz")
  else: print(x)

# Ejercicio III:
def calcular_descuento (total):
  if total >= 1000:
    print(total-total*0.2)
  elif total>=500:
    print(total-total*0.1)
  else:
    print(total)

calcular_descuento(1200)

calcular_descuento(750)

calcular_descuento(300)

"""IV.Crea una función llamada clasificar_edad() que reciba como parámetro la edad de una
persona. La función debe clasificar a la persona en una de las siguientes categorías:
"Niño" si la edad es menor de 12 años.
"Adolescente" si la edad está entre 12 y 17 años.
“Joven” si la edad está entre 18 y 24 años.
"Adulto" si la edad está entre 25 y 64 años.
"Adulto Mayor" si la edad es mayor o igual a 65 años.
La función debe devolver la categoría correspondiente. Prueba la función con las edades de
10, 19, 25 y 70.
"""

#EJERCICIO IV
def clasificar_edad(edad):
  edad = int(input("Escribe edad: "))
  if edad < 12: return print("Niño")
  if 12<=edad<=17:return print("Adolescente")
  if 18<=edad<=24: return print("Joven")
  if 25<=edad<=64: return print("Adulto")
  if edad>=65: return print("Adulto Mayor")

clasificar_edad(21)

"""**ejercicio** V

Crea una función 𝒄𝒂𝒍𝒄𝒖𝒍𝒂𝒓_𝒄𝒓𝒂𝒆𝒔𝒕(𝒎𝒆𝒅𝒊𝒂_𝒑𝒆𝒓𝒔𝒐𝒏𝒂𝒍,𝒎𝒆𝒅𝒊𝒂_𝒄𝒖𝒓𝒔𝒐,𝒅𝒆𝒔𝒗𝒊𝒂𝒄𝒊𝒐𝒏_𝒄𝒖𝒓𝒔𝒐) que
reciba como tres únicos inputs tu media, la media del curso y la desviación estándar del curso
y te devuelva tu craest calculado. No te olvides documentar la función usando triple comillas
“””.
"""

def calcular_craest( media_personal, media_curso, desviacion_curso):
  '''
  Calcular el CRAEST de una persona dado su media personal, media del curso y la desviacion del curso

  Parametros:
  media_personal (float): La media personal de la persona.
  media_curso (float): La media del curso.
  desviacion_curso (float): La desviacion del curso.

  Devuelve:
  craest (float): el CRAEST de la persona.
  return craest
  '''
  craest = (media_personal-media_curso)*10/desviacion_curso+50
  return craest

media_personal: 16
media_curso: 15
desviacion_curso: 3
calcular_craest( media_personal=16, media_curso=15, desviacion_curso=3)